### ISSUE TITLE
[Import] Primary Key on object_resolver not working

### ISSUE THREAD

**Issue by ivanmerta** [w-vision/ImportDefinitions#152]
Hi Dominik,

I am having import definitions with 'create new version on every run' set.
As I understand the existence of object is resolved by defined primary keys. In my case one of the primary key is many-to-one relation field having object_resolver interpreter.

The import is then failing eg with this error:
`import_definition.status: Error: An exception occurred while executing 'SELECT object_3.o_id as o_id, `object_3`.`o_type` FROM `object_3` WHERE (`StateName` = ? AND `StateId` = ? AND `StateDescription` = ? AND `Country` = ? AND  object_3.o_type IN ('variant','object','folder'))' with params ["Andhra Pradesh", "AP", "Andhra Pradesh", "IND"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Country' in 'where clause' [] []`

Is there a way to support this use case?
Also, this seems to be failing also for other cases when I have different interpreters on fields.

Thanks!

**Comment by dpfaffenbauer** [comment]
loading the object happens before running interpreters, having the primary key on a multi-href field doesn't work therefore. What you can do is, create your own loading like:

```php
<?php

namespace AppBundle\ImportDefinitions\Loader;

use Doctrine\DBAL\Connection;
use ImportDefinitionsBundle\Loader\LoaderInterface;
use ImportDefinitionsBundle\Model\DefinitionInterface;
use Pimcore\Model\DataObject\Concrete;

final class RockyMountainSpecLoader implements LoaderInterface
{
    /**
     * @var Connection
     */
    private $connection;

    /**
     * @param Connection $connection
     */
    public function __construct(Connection $connection)
    {
        $this->connection = $connection;
    }

    public function load(string $class, $data, DefinitionInterface $definition, $params): ?Concrete
    {
        $classObject = '\Pimcore\Model\DataObject\\' . ucfirst($class);

        $sql = "SELECT * FROM properties WHERE `name`='rocky_mountain_master_sku' AND ctype='object' AND `data`='".$data['SKU']."'";

        $result = $this->connection->fetchAll($sql);

        if (count($result) === 0 || count($result) > 1) {
            return null;
        }

        return $classObject::getById($result[0]['cid']);
    }
}

```

in this case, I load the object based on a pimcore property.

you have to register that of course to the container:

```yml
app.import_definition.loader.rocky_mountain_spec:
        class: AppBundle\ImportDefinitions\Loader\RockyMountainSpecLoader
        arguments:
            - '@doctrine.dbal.default_connection'
        tags:
            - { name: import_definition.loader, type: rocky_spec }
```
